strings = {
    'invalid_domain_ip': ' is not a valid domain or IP, please try again',
    'unresolved_domain_ip': ' is not available or cannot be reached right now, please check and try again later',
    'domain_required': 'Domain is required to scan',
    'auth': 'Authorization',
    'status_queued': 'queued',
    'status_running': 'running',
    'status_finished': 'finished',
    'database_issue': 'Database connection issue',
    'blacklist': 'blacklist',
    'rdp': 'rdp',
    'key_value': 'value',
    'mongo_value': 'value',
    'input_force': 'force',
    'error': 'error',
    'output_ntlm': 'ntlm',
    'message': 'message',
    'error_enum': 'error_enum',
    'error_ntlm': 'error_ntlm'
}
