language: python

dist: xenial

services:
  - docker

env:
  global:
    - IMAGE_NAME=dhsncats/trustymail1.py
    - DOCKER_USER=jsf9k
    - secure: "IAbtmubLq2hL71aollQEfoV+t9Zbqn4rNVqi5YNerqxvXr6WiDzwmYUujOCnQiHli8xkIU0J8OSPX0aA4cOTxPGiZeNguGuVWmR2ZCB8SMyjbKJOEIpLZv/jG1Be6dVXiJwKwQM3yX4pqPfLIuYkE6S1GAodudPzcJ8xM/h1qzJijknJEqsCJQw43zSHZ/epYulgWcmnCAmaoehZTCjVcW4l8iyVHSNfgO7gu5iWC9y4AIIX96E9TZkSDeud1yqUcORMwfdOl2pHhDh3KnF8HZSOCetTHP7JacLUMJiiCpKN34Xn9RQgjbVKOrF/rcC8WEDrWKn14SFfgUP0dl6lCr6P9HE4aHKvrH/nCyflFOANbEKMywE8DzNA3zd7MC0HQkyb40LAiBSbTD58myUsc+WlmaZyvpJ7akukbmVjVPQWNvs1laz/bqyLdPh4WMqgOTbP7BrgDeIrCVedwdvhqq9KEaoak8RBs/Wb8LisI6j+vAY/HKlVnuIXRL0RNGTko96kBluEpAsWDjls39Hmu5hl1glbqCWDW9+dE0/Zx4MuSt4OVAywMW+lzxA16SdqDLCZqGv00vnPpxuBAvEEQbVtsmQ6lR+fwTYKFEDZM7axRwBlLzIDEzSoz4K0fSq3EuU4mkoVZKcHGnuHuRqaNhce0zzZx3lHdNTm7oa7b0U="

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install -y shellcheck

install:
  - pip install flake8 pytest-cov pytest coveralls
  - pip install --editable .

script:
  - shellcheck bump_version.sh tag.sh travis_scripts/*.sh
  - pytest --cov=trustymail1.py
  - flake8 .
  # - bash travis_scripts/build_docker_image.sh

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: jsf9k
    password:
      secure: a1ZOoVl8PVCqWVuqO9v9Y4CZqrNepir9m+MfEBgQuFZrc45zGPmHMbAIfHOETLuEozBx1Dn5gTtssitMMpJmDia8sNkXh+yBuTOlO0zCL9iGIfH/Ul4Z38LshKuSKIbQnO3aedDSo05iP+7L4/ae1zna29E75vLeU3nwgJH6lLAOB0g5tYZPiul/F7UDFBONgsFb0VnM7S3L6e7yUZh0CZ61KARPjKFGqOzXShJWVhoTW3PUn43AzsgUXM8DY2BJX740ks4YOcTIBpbq1+g7KWrL2XZD0vws0vtbqm+HL045fgshOqAzeINf2D5G/yh72YBULlthXCU0pqk4C83///5WL/3PRFv/EYoPnfRq5/Kcmg2qYd5YvrLh1gEz9Aq97+cd1pXXhJh0lK/bNrP7q7/+X1+37eVTriZ1g2FVazBpLjM7JAOT1SZ8HqHm0TInMDSAlQ8aAn2Yke4IziG2v6v9OuOdsEk0yZNI1pEZNVrvS3cXXEe1M+a5VZGOfluqFOLY/xuD6f3tLPHLdSr9Ujw4Fb4naGyIYY4/dCa3K9ATlCk9CyDoqQ+LNm8jOrDdyCALK9S40waoBgMgYjddO+Jb1gn3GtIaH34CIzjSvxry41oACCYMEP3ej3lJ44ZAfOefT22suW9c4ryX/2QS/Hq+k7fAwgM+Q2z69Ysbac4=
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: '3.8'
  # - provider: script
  #   script: bash travis_scripts/deploy_to_docker_hub.sh
  #   on:
  #     tags: true
  #     python: '3.6'
